<?php

return [
    [
        "title" => 'Casa Sesto San Giovanni',
        "description" => 'Appartamento spazioso nel cuore di Sesto San Giovanni',
        "address" => 'Via Roma 15, 20099 Sesto San Giovanni',
        "latitude" => '45.53767',
        "longitude" => '9.23827',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Appartamento Monza',
        "description" => 'Luminoso appartamento con vista sul parco a Monza',
        "address" => 'Viale Regina Margherita 10, 20900 Monza',
        "latitude" => '45.58148',
        "longitude" => '9.27477',
        "rooms" => 2,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Casa Cinisello Balsamo',
        "description" => 'Accogliente casa vicino al centro di Cinisello Balsamo',
        "address" => 'Via Vittorio Emanuele 25, 20092 Cinisello Balsamo',
        "latitude" => '45.54789',
        "longitude" => '9.22157',
        "rooms" => 2,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Villa Nova Milanese',
        "description" => 'Spaziosa villa con giardino a Nova Milanese',
        "address" => 'Via Garibaldi 50, 20834 Nova Milanese',
        "latitude" => '45.58122',
        "longitude" => '9.15173',
        "rooms" => 5,
        "beds" => 5,
        "bathrooms" => 1,
        "mq" => 100,
        "is_visible" => true,
        "price" => 300.00,
    ],
    [
        "title" => 'Appartamento Rozzano',
        "description" => 'Appartamento moderno in zona tranquilla a Rozzano',
        "address" => 'Via Martiri di Cefalonia 8, 20089 Rozzano',
        "latitude" => '45.36168',
        "longitude" => '9.10997',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 95,
        "is_visible" => true,
        "price" => 280.00,
    ],
    [
        "title" => 'Casa Pioltello',
        "description" => 'Casa con ampio giardino a Pioltello',
        "address" => 'Via XX Settembre 3, 20096 Pioltello',
        "latitude" => '45.51476',
        "longitude" => '9.31794',
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "mq" => 120,
        "is_visible" => true,
        "price" => 350.00,
    ],
    [
        "title" => 'Villa Legnano',
        "description" => 'Elegante villa con piscina a Legnano',
        "address" => 'Via Roma 45, 20025 Legnano',
        "latitude" => '45.60059',
        "longitude" => '8.92262',
        "rooms" => 5,
        "beds" => 4,
        "bathrooms" => 3,
        "mq" => 200,
        "is_visible" => true,
        "price" => 600.00,
    ],
    [
        "title" => 'Appartamento Cologno Monzese',
        "description" => 'Moderno appartamento a Cologno Monzese',
        "address" => 'Via Milano 10, 20093 Cologno Monzese',
        "latitude" => '45.53685',
        "longitude" => '9.28126',
        "rooms" => 2,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 85,
        "is_visible" => true,
        "price" => 270.00,
    ],
    [
        "title" => 'Casa Lainate',
        "description" => 'Ampia casa con vista sul parco di Lainate',
        "address" => 'Via Garibaldi 35, 20020 Lainate',
        "latitude" => '45.55576',
        "longitude" => '8.94117',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 90,
        "is_visible" => true,
        "price" => 260.00,
    ],
    [
        "title" => 'Villa Arese',
        "description" => 'Villa con piscina nel verde di Arese',
        "address" => 'Via della Vittoria 20, 20020 Arese',
        "latitude" => '45.55317',
        "longitude" => '9.05657',
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "mq" => 160,
        "is_visible" => true,
        "price" => 480.00,
    ],
    [
        "title" => 'Appartamento Rho',
        "description" => 'Appartamento luminoso nel centro di Rho',
        "address" => 'Piazza della Repubblica 5, 20017 Rho',
        "latitude" => '45.52951',
        "longitude" => '8.92624',
        "rooms" => 2,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 75,
        "is_visible" => true,
        "price" => 230.00,
    ],
    [
        "title" => 'Casa Buccinasco',
        "description" => 'Casa spaziosa con giardino a Buccinasco',
        "address" => 'Via Diaz 15, 20090 Buccinasco',
        "latitude" => '45.39976',
        "longitude" => '9.07055',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 90,
        "is_visible" => true,
        "price" => 270.00,
    ],
    [
        "title" => 'Villa Cernusco sul Naviglio',
        "description" => 'Villa elegante con piscina a Cernusco sul Naviglio',
        "address" => 'Via Manzoni 30, 20063 Cernusco sul Naviglio',
        "latitude" => '45.54333',
        "longitude" => '9.33123',
        "rooms" => 5,
        "beds" => 4,
        "bathrooms" => 3,
        "mq" => 200,
        "is_visible" => true,
        "price" => 600.00,
    ],
    [
        "title" => 'Appartamento Segrate',
        "description" => 'Appartamento moderno a Segrate',
        "address" => 'Via Dei Ciliegi 12, 20090 Segrate',
        "latitude" => '45.49523',
        "longitude" => '9.28279',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 80,
        "is_visible" => true,
        "price" => 250.00,
    ],
    [
        "title" => 'Casa Gorgonzola',
        "description" => 'Ampia casa nel centro storico di Gorgonzola',
        "address" => 'Piazza Martiri della Libertà 8, 20064 Gorgonzola',
        "latitude" => '45.52787',
        "longitude" => '9.43227',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 85,
        "is_visible" => true,
        "price" => 260.00,
    ],
    [
        "title" => 'Villa Settimo Milanese',
        "description" => 'Villa con piscina a Settimo Milanese',
        "address" => 'Via Vittorio Veneto 55, 20019 Settimo Milanese',
        "latitude" => '45.49689',
        "longitude" => '9.05686',
        "rooms" => 4,
        "beds" => 3,
        "bathrooms" => 2,
        "mq" => 120,
        "is_visible" => true,
        "price" => 350.00,
    ],
    [
        "title" => 'Appartamento Cornaredo',
        "description" => 'Appartamento moderno a Cornaredo',
        "address" => 'Via Cavour 7, 20010 Cornaredo',
        "latitude" => '45.48348',
        "longitude" => '8.95698',
        "rooms" => 2,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 90,
        "is_visible" => true,
        "price" => 280.00,
    ],
    [
        "title" => 'Casa Cusano Milanino',
        "description" => 'Casa accogliente a Cusano Milanino',
        "address" => 'Via Garibaldi 20, 20095 Cusano Milanino',
        "latitude" => '45.56302',
        "longitude" => '9.16436',
        "rooms" => 3,
        "beds" => 2,
        "bathrooms" => 1,
        "mq" => 95,
        "is_visible" => true,
        "price" => 260.00,
    ]
];
